[package]
name = "pixel_rendering"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pix-win-loop = "0.4.0"
clipline = "0.2.0"
glam = "0.25.0"